// 'use client';
import { Inter } from 'next/font/google';
import classNames from 'classnames/bind';
import '~/app/globals.css';

import styles from './layout.module.scss';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'VJP LightBox',
    description: 'Generated by Next.js',
};

export default function PageLayout({ children }) {
    return (
        <div className={cx('wrapper')}>
            <div className={cx('container')}>
                <div className={cx('content')}>
                    <main>{children}</main>
                </div>
            </div>
        </div>
    );
}
