import { Inter } from 'next/font/google';
import classNames from 'classnames/bind';
import '~/app/globals.css';

import Header from '~/app/components/Layouts/components/Header';
import Footer from '~/app/components/Layouts/components/Footer';

import styles from './layout.module.scss';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'VJP Connect Platform',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <div className={cx('wrapper')}>
                    <Header />
                    <div className={cx('container')}>
                        <div className={cx('content')}>
                            <main>{children}</main>
                        </div>
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
